language: python
python:
    - 2.7
git:
    depth: 3
branches:
    only:
        - master
addons:
    apt:
        packages:
            - libclang-common-dev # needed for grpcio
before_install:
    - sudo apt-get update
    - pip install --upgrade pip
    - pip install grpcio # for some reason, this doesn't compile right when called by setup.py.
    - sudo locale-gen en_US en_US.utf8 # ensure our expected locales exist
install: python setup.py install
before_script:
    - chmod o-rwx ~/.python-eggs # silence a warning from virtualenv
script: nose2
